export const driverUpdatedKeys = {
  address: "Address",
  state: "State",
  driver_license_id: "Driver License ID",
  expiry_date: "Expiry Date",
  issued_date: "Date Of Issue",
  last_name: "Last Name",
  first_name: "First Name",
  date_of_birth: "Date Of Birth",
  restrictions: "Restrictions",
  endorsements: "Endorsements",
  dl_class: "Driver License Class",
  sex: "Sex",
  weight: "Weight",
  height: "Height",
  hair_color: "Hair Color",
  eye_color: "Eye Color",
  dd_number: "Document Discriminator",
};
