export const receiptUpdatedKeys = {
  total_amount: "Total amount",
  total_tax: "Total tax",
  tip: "Tip",
  total_net: "Total net",
  category: "Category",
  subcategory: "Subcategory",
  date: "Purchase Date",
  time: "Purchase Time",
  supplier_name: "Supplier name",
  supplier_address: "Supplier address",
  supplier_phone_number: "Supplier phone",
  supplier_company_registrations: "Supplier IDs",
  document_type: "Document type",
  locale: "Language",
};
